version: "3"
services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6666:3306"
